/**
 * Standalone entry point for the bundled `monitor-dashboard.exe`.
 *
 * This is the source that esbuild bundles (with every workspace/npm dependency
 * inlined) into a single CommonJS file, which Node's SEA tooling then fuses into
 * a copy of node.exe. See packaging/build-exe.mjs.
 *
 * It differs from packages/server/src/cli.ts in three ways, all to suit a
 * double-clickable desktop binary rather than a dev-run CLI:
 *   1. The dashboard's static assets are embedded (assets.json, generated at
 *      build time) and written to a temp dir at startup — the fused exe has no
 *      `public/` folder on disk to read from.
 *   2. With no token supplied it defaults to loopback + no-auth so a fresh
 *      double-click "just works" locally. (resolveServerConfig still refuses to
 *      bind a public interface without a token, so this stays safe.)
 *   3. On a successful loopback bind it opens the default browser.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import { MonitorToolError } from '@rgm-power-tools/core';
import {
  resolveServerConfig,
  ServerConfigError,
  createServer,
} from '@rgm-power-tools/server';
// Generated by packaging/build-exe.mjs from packages/server/public/*.
import ASSETS from './.generated/assets.json' with { type: 'json' };

const VERSION = '0.1.0';

const HELP = `monitor-dashboard ${VERSION}
Self-hostable dashboard and JSON API for the RGM Power Tools (standalone build).

Usage:
  monitor-dashboard.exe [options]

Options:
  --host <host>        interface to bind (default: 127.0.0.1)
  --port <port>        TCP port (default: 4570)
  --token <token>      dashboard bearer token (or set DASHBOARD_TOKEN)
  --workdir <dir>      where monitor-config.yaml / monitor-tags.yaml live
  --no-auth            run without a token (loopback only)
  --no-open            do not open a browser on startup
  -V, --version        print version
  -h, --help           show this help

With no --token / DASHBOARD_TOKEN and no --no-auth, the dashboard starts on
loopback without auth and opens your browser. To expose it on the network, set
a token (at least 16 chars) with --token or DASHBOARD_TOKEN.

Environment:
  DASHBOARD_TOKEN, DASHBOARD_HOST, DASHBOARD_PORT, RGM_WORKDIR,
  MONITOR_URL, MONITOR_AUTH_TOKEN
`;

/** Local copy of config.isPublicHost (not exported from the package surface). */
function isPublicHost(host) {
  return host !== '127.0.0.1' && host !== 'localhost' && host !== '::1';
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case '--host':
        args.host = argv[++i];
        break;
      case '--port':
        args.port = argv[++i];
        break;
      case '--token':
        args.token = argv[++i];
        break;
      case '--workdir':
        args.workdir = argv[++i];
        break;
      case '--no-auth':
        args.noAuth = true;
        break;
      case '--no-open':
        args.noOpen = true;
        break;
      case '-V':
      case '--version':
        args.version = true;
        break;
      case '-h':
      case '--help':
        args.help = true;
        break;
      default:
        throw new ServerConfigError(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

/** Write the embedded dashboard assets to a temp dir and return its path. */
function extractAssets() {
  const dir = join(tmpdir(), 'rgm-dashboard-public', VERSION);
  mkdirSync(dir, { recursive: true });
  for (const [name, b64] of Object.entries(ASSETS)) {
    writeFileSync(join(dir, name), Buffer.from(b64, 'base64'));
  }
  return dir;
}

/** Open the given URL in the user's default browser (best effort, Windows). */
function openBrowser(url) {
  try {
    // `cmd /c start "" <url>` — the empty title arg avoids start treating a
    // quoted URL as the window title.
    spawn('cmd', ['/c', 'start', '', url], {
      detached: true,
      stdio: 'ignore',
    }).unref();
  } catch {
    // Opening the browser is a convenience; never fail the server over it.
  }
}

function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (err) {
    console.error(`✗ ${err.message}`);
    console.error('Run with --help for usage.');
    process.exitCode = 1;
    return;
  }

  if (args.help) {
    console.log(HELP);
    return;
  }
  if (args.version) {
    console.log(VERSION);
    return;
  }

  const hasToken = Boolean(args.token || process.env.DASHBOARD_TOKEN);

  let config;
  try {
    config = resolveServerConfig({
      host: args.host,
      port: args.port,
      token: args.token,
      workdir: args.workdir,
      // No token anywhere → default to no-auth (loopback only; the resolver
      // still refuses a public bind without a token).
      allowNoAuth: args.noAuth ?? !hasToken,
    });
  } catch (err) {
    if (err instanceof MonitorToolError) {
      console.error(`✗ ${err.message}`);
      process.exitCode = 1;
      return;
    }
    throw err;
  }

  const publicDir = extractAssets();
  const server = createServer({ config, publicDir });

  server.on('error', (err) => {
    console.error(`✗ ${err.message}`);
    process.exitCode = 1;
  });

  server.listen(config.port, config.host, () => {
    const url = `http://${config.host}:${config.port}`;
    const auth = config.token ? 'token auth enabled' : 'AUTH DISABLED';
    console.log(`RGM Power Tools dashboard listening on ${url} (${auth})`);
    console.log(`Working directory: ${config.workdir}`);
    if (!config.token) {
      console.warn(
        '⚠  Running without a token. Anyone who can reach this port can ' +
          'drive your Monitor instance. Use only on a trusted local machine.',
      );
    }
    if (isPublicHost(config.host)) {
      console.warn(
        `⚠  Bound to ${config.host} — the dashboard is reachable ` +
          'off-host. Ensure it sits behind TLS/a reverse proxy and a strong token.',
      );
    }
    if (!args.noOpen && !isPublicHost(config.host)) {
      openBrowser(url);
    }
    console.log('\nPress Ctrl+C to stop.');
  });
}

main();
